define('USER_ITEMS_PROPERTY_TEST', array(
	'one' => 'これはテスト',
	'two' => 'です',
));

const USER_ITEMS_PROPERTY = array (
	'id' =>
		array('alias' => 'id',
			  'min_length' => '',
			  'max_length' => '',
			  'is_required' => '',
			  'item_type' => 'text',
			  'is_inputtable' => false,
			  'ref_const_name' => '',
			  'rows' => '',
			  'cols' => '',
			  'placeholder' => '',
			  'size' => '',
			  'date_format' => '',
			  'sort_order' => 10,
		),

	'name' =>
		array('alias' => '氏名',
			  'min_length' => '',
			  'max_length' => 50,
			  'is_required' => true,
			  'item_type' => 'text',
			  'is_inputtable' => true,
			  'ref_const_name' => '',
			  'rows' => '',
			  'cols' => '',
			  'placeholder' => '',
			  'size' => '',
			  'date_format' => '',
			  'sort_order' => 20,
		),

	'login_id' =>
		array('alias' => 'ログインID',
			  'min_length' => '',
			  'max_length' => 50,
			  'is_required' => true,
			  'item_type' => 'text',
			  'is_inputtable' => true,
			  'ref_const_name' => '',
			  'rows' => '',
			  'cols' => '',
			  'placeholder' => '',
			  'size' => '',
			  'date_format' => '',
			  'sort_order' => 30,
		),

	'password' =>
		array('alias' => 'パスワード',
			  'min_length' => '', //★←開発しづらいので空文字にしておく。最終的には10にしようと思う。
			  'max_length' => 20,	
			  'is_required' => true,
			  'item_type' => 'password',
			  'is_inputtable' => true,
			  'ref_const_name' => '',
			  'rows' => '',
			  'cols' => '',
			  'placeholder' => '',
			  'size' => '',
			  'date_format' => '',
			  'sort_order' => 40,
		),

	'auth_type' =>
		array('alias' => '権限種別',
			  'min_length' => '',
			  'max_length' => '',
			  'is_required' => true,
			  'item_type' => 'selectbox',
			  'is_inputtable' => true,
			  'ref_const_name' => 'AUTH_TYPE',
			  'rows' => '',
			  'cols' => '',
			  'placeholder' => '',
			  'size' => '',
			  'date_format' => '',
			  'sort_order' => 50,
		),

	'note' =>
		array('alias' => '備考',
			  'min_length' => '',
			  'max_length' =>  255,
			  'is_required' => false,
			  'item_type' => 'textarea',
			  'is_inputtable' => true,
			  'ref_const_name' => '',
			  'rows' => 7,
			  'cols' => 60,
			  'placeholder' => '',
			  'size' => '',
			  'date_format' => '',
			  'sort_order' => 60,
		),

	'create_date' =>
		array('alias' => '作成日時',
			  'min_length' => '',
			  'max_length' =>  '',
			  'is_required' => '',
			  'item_type' => 'text',
			  'is_inputtable' => false,
			  'ref_const_name' => '',
			  'rows' => '',
			  'cols' => '',
			  'placeholder' => '',
			  'size' => '',
	 		  'date_format' => 'Y/m/d H:i:s',
	 		  'sort_order' => 70,
	),

	'create_user_id' =>
		array('alias' => '作成者ID',
			  'min_length' => '',
			  'max_length' =>  '',
			  'is_required' => '',
			  'item_type' => 'text',
			  'is_inputtable' => false,
			  'ref_const_name' => '',
			  'rows' => '',
			  'cols' => '',
			  'placeholder' => '',
			  'size' => '',
	 		  'date_format' => '',
	 		  'sort_order' => 80,
	),

	'update_date' =>
		array('alias' => '更新日時',
			  'min_length' => '',
			  'max_length' =>  '',
			  'is_required' => '',
			  'item_type' => 'text',
			  'is_inputtable' => false,
			  'ref_const_name' => '',
			  'rows' => '',
			  'cols' => '',
			  'placeholder' => '',
			  'size' => '',
	 		  'date_format' => 'Y/m/d H:i:s',
	 		  'sort_order' => 90,
	),

	'update_user_id' =>
		array('alias' => '更新者ID',
			  'min_length' => '',
			  'max_length' =>  '',
			  'is_required' => '',
			  'item_type' => 'text',
			  'is_inputtable' => false,
			  'ref_const_name' => '',
			  'rows' => '',
			  'cols' => '',
			  'placeholder' => '',
			  'size' => '',
	 		  'date_format' => '',
	 		  'sort_order' => 100,
	),

);
